name: Maven Test # Nom del workflow

on:
  push:
    branches: [ "main" ] # Executar el workflow quan es fa un push a la branca "main"
  pull_request:
    branches: [ "main" ] # Executar el workflow quan es fa un pull request cap a "main"

jobs:
  build: # Definició del treball "build"

    runs-on: ubuntu-latest # Especifica que el workflow s'executarà en un entorn Ubuntu actualitzat

    steps:
    - uses: actions/checkout@v6 # Acció per obtenir el codi del repositori

    - name: Set up JDK 21
      uses: actions/setup-java@v6 # Configura l'entorn de Java
      with:
        java-version: '21' # Especifica la versió de Java JDK 21
        distribution: 'temurin' # Utilitza la distribució Temurin d'Adoptium
        cache: maven # Activa la memòria cau de Maven per accelerar el procés

    - name: Run tests with Maven
      run: mvn test # Executa Maven en mode test per compilar i provar el projecte
